name : My First Yaml File

on :
    push :
        branches : ['main']
    pull_request : 
        branches : ['main']

jobs :
    build : 
        runs-on : ubuntu-latest
        strategy :
            matrix :
                node-version : [14.x, 16.x, 18.x]

        steps : 
        - uses : actions/checkout@v4
        - name : Use NodeJS ${{matrix.node-version}}
          uses : actions/setup-node@v3
          with :
            node-version : ${{matrix.node-version}}
            cache : npm

        - name : "Install Dependancies"
          run : npm i
          
        - name : "Running Test"
          run : npm run test